# -----------------------------
# Project configuration
# -----------------------------

generator:
  transactions_per_batch: 100
  sleep_seconds: 2

  normal_min_amount: 1.00
  normal_max_amount: 500.00

  outlier_probability: 0.001
  outlier_min_amount: -500.00
  outlier_max_amount: 4000.00

  negative_amount_probability: 0.3
  negative_min_amount: 1.00
  negative_max_amount: 300.00


  error_types:
    - "Bad Card Number"
    - "Bad CVV"
    - "Bad Expiration Date"
    - "Bad PIN"
    - "Bad PIN, Insufficient Balance"
    - "Bad PIN, Technical Glitch"
    - "Insufficient Balance"
    - "Technical Glitch"

  error_probability: 0.016
  null_value_probability: 0.02

  merchant_reference_path: "data/raw/kaggle_card_transactions/merchant_reference.csv"

  

